# _config.yml - Cloudflare Pages高定版

# ---------------------------
# 核心配置
# ---------------------------
title: LUXE CHRONICLE
subtitle: 智识精英的数字会所
description: 融合加密金融与高定生活的Web3内容枢纽
keywords:
  - 资产代币化
  - 数字身份
  - 腕表NFT
  - 太空经济
  - 量子金融
author: Victor Laurent
language: zh-CN
timezone: Asia/Shanghai
url: https://your-project.pages.dev
root: /

# ---------------------------
# 部署配置
# ---------------------------
deploy:
  - type: git
    repo: https://github.com/yourname/your-repo
    branch: main

# ---------------------------
# 云原生优化
# ---------------------------
cloudflare:
  workers: true
  analytics: true
  cache_ttl: 14400

# ---------------------------
# 高定视觉配置
# ---------------------------
theme: luxe-pro
theme_config:
  # 色彩方案
  colors:
    primary: "#1a365d"  # 深海蓝
    secondary: "#c5a47e"  # 香槟金
    accent: "#0d1a26"  # 午夜黑
  
  # 字体配置
  fonts:
    header: "https://fonts.luxe-cdn.com/HelveticaNow.woff2"
    body: "https://fonts.luxe-cdn.com/Sohne-Book.woff2"
  
  # 动效参数
  effects:
    parallax_intensity: 0.75
    hover_shadow: true
  
  # VIP入口
  vip_gateway: 
    enable: true
    redirect: /members-only

# ---------------------------
# 安全增强
# ---------------------------
security_headers:
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Permissions-Policy: "geolocation=(), microphone=()"

# ---------------------------
# 构建优化
# ---------------------------
minify:
  html:
    enable: true
  css:
    enable: true
    exclude:
      - '*.min.css'
  js:
    enable: true
    mangle: true

# ---------------------------
# 高级路由
# ---------------------------
permalink: :year/:title/
pretty_urls:
  trailing_index: false
  trailing_html: false

# ---------------------------
# 会员体系
# ---------------------------
membership:
  tiers:
    - name: 星耀会员
      icon: diamond
      threshold: 1000000
    - name: 寰宇会籍
      icon: galaxy
      threshold: 10000000

# ---------------------------
# 数据源配置
# ---------------------------
external_data:
  bloomberg_api: https://api.bloomberg.luxe/v3
  sothebys_feed: https://feed.sothebys.luxe/auctions
