# ---------------------------
# Hexo Theme Solitude - 精英定制版
# Modified for LuxeChronicle
# ---------------------------

### 基础配置
## 强化品牌识别与精英定位 ##

# --------------------------- 网站信息 start ---------------------------
site:
  name:
    class: text 
    custom: LuxeChronicle  # 英文品牌标识
  icon: /images/luxe-icon.svg  # 替换为定制SVG徽章
# --------------------------- 网站信息 end ---------------------------

# --------------------------- 导航栏 start ---------------------------
nav:
  group:
    VIP通道: https://club.luxe-chronicle.com || fas fa-diamond  # 会员专属入口

  menu:  # 重构导航结构
    财富洞见: 
      资产配置: /wealth/ || fas fa-coins
      私募股权: /private-equity/ || fas fa-chart-line
      数字资产: /digital-assets/ || fas fa-bitcoin
    精英生活:
      游艇鉴赏: /yachting/ || fas fa-sailboat
      腕表收藏: /watches/ || fas fa-clock
      私人航空: /aviation/ || fas fa-jet-fighter
    圈层服务:
      家族办公室: /family-office/ || fas fa-chess-queen
      活动邀约: /events/ || fas fa-calendar-star
      白手套服务: /concierge/ || fas fa-ring

  right:  # 强化隐私控制
    random: false
    custom:
      - name: 安全登出
        url: /logout/
        icon: fas fa-lock
# --------------------------- 导航栏 end ---------------------------

# --------------------------- 首页顶部 start ---------------------------
hometop:
  enable: true
  banner:
    title: 智识精英的私享领地
    url: 您的黑卡会员资格已激活
    icon:  # 高端服务标识
      私人银行: 
        img: /images/private-banking.svg
        color: "#1a365d"
      百达翡丽授权: 
        img: /images/patek-auth.svg 
        color: "#c5a47e"
  group:  # 热点访问入口
    本月精选: /monthly-picks/ || fas fa-gem || linear-gradient(135deg, #1a365d 0%, #0c1a2d 100%)
# --------------------------- 首页顶部 end ---------------------------

### 视觉呈现优化
## 采用奢侈品视觉语言 ##

# --------------------------- 主题颜色 start ---------------------------
theme_color:
  dark: "#c5a47e"  # 香槟金（暗模式）
  light: "#1a365d"  # 深海蓝（亮模式）
# --------------------------- 主题颜色 end ---------------------------

# --------------------------- 字体 start ---------------------------
font:
  font-family: "Helvetica Now Display, PingFang SC"  # 付费商业字体
  code-font-family: "JetBrains Mono, Consolas"  # 开发者友好字体
# --------------------------- 字体 end ---------------------------

# --------------------------- 侧边栏 start ---------------------------
aside:
  card:
    style: 2  # 选用VIP样式
    author:
      img: /images/chief-advisor.jpg  # 专业形象照
      sticker: /images/verified-badge.svg  # 认证徽章
    background: linear-gradient(135deg, #1a365d 0%, #0c1a2d 100%)  # 深海渐变
    content: 首席财富顾问
    content2: CFA | 家族办公室专家
    information:  # 精英社交入口
      LinkedIn: https://linkedin.com/in/victorlaurent || fab fa-linkedin
      Bloomberg终端: /bloomberg-access/ || fas fa-terminal
# --------------------------- 侧边栏 end ---------------------------

### 功能增强
## 高净值用户专属功能 ##

# --------------------------- 安全增强 start ---------------------------
extends:
  head:  # 添加安全策略
    - <meta http-equiv="Content-Security-Policy" content="default-src 'self' *.luxe-chronicle.com">
    - <meta http-equiv="Strict-Transport-Security" content="max-age=63072000">
# --------------------------- 安全增强 end ---------------------------

# --------------------------- 会员系统 start ---------------------------
custom_fields:  # 新增字段
  membership:
    tiers:
      - name: 铂金会员
        min_assets: 10000000
        color: "#c5a47e"
      - name: 钻石会员  
        min_assets: 50000000
        color: "#1a365d"
    concierge_phone: 400-900-8888
# --------------------------- 会员系统 end ---------------------------

# --------------------------- 搜索系统 start ---------------------------
search:
  type: algolia
  algolia:  # 需替换实际API密钥
    appId: "YOUR_APP_ID"
    apiKey: "YOUR_SEARCH_KEY"
    indexName: "luxe_prod"
    hits:
      per_page: 8  # 精准搜索结果数
# --------------------------- 搜索系统 end ---------------------------

# --------------------------- 评论系统 start ---------------------------
comment:
  use: waline
  waline:  # 私有化部署配置
    envId: https://comment.luxe-chronicle.com
    option:
      login: "disable"  # 仅限邀请注册
      wordLimit: 300  # 评论长度限制
      reaction: ["/images/diamond.svg"]  # 定制反应图标
# --------------------------- 评论系统 end ---------------------------

# --------------------------- 页脚 start ---------------------------
footer:
  information:
    author: /images/footer-logo.svg  # 品牌标志
    left:  # 金融服务入口
      私人银行: https://bank.luxe-chronicle.com || fas fa-vault
      税务规划: /tax-optimization/ || fas fa-percent
    right:  # 媒体合作伙伴
      经济学人订阅: https://econ.luxe-chronicle.com || fas fa-newspaper
      CNBC直连: /cnbc-pro/ || fas fa-satellite-dish

  group:  # 法律条款
    会员协议: 
      隐私条款: /privacy/
      反洗钱声明: /aml-policy/
# --------------------------- 页脚 end ---------------------------

### 高级功能
## 智能化与个性化 ##

# --------------------------- AI摘要 start ---------------------------
post_ai:
  enable: true
  modelName: Claude-3-Opus
  tips: 本文摘要经私人银行AI审核，仅限会员查看完整分析
# --------------------------- AI摘要 end ---------------------------

# --------------------------- 数据分析 start ---------------------------
google_adsense:  # 高净值广告配置
  enable: true
  client: "ca-pub-XXXXXX"
  slot: "YYYYYY"
  post_content: false  # 禁用文章内广告
# --------------------------- 数据分析 end ---------------------------
