# Site
title: LuxeChronicle  # 英文品牌名提升国际感，中文可译为"奢华纪事"
subtitle: '精英阶层的数字名片'  # 副标题强调用户定位
description: '探索财富管理、奢侈科技与精英生活方式的深度博客'  # 更精准的定位描述
keywords: 
- 财富自由
- 高端社交
- 奢侈科技
- 私人游艇
- 腕表收藏  # 高净值人群关注的关键词
author: Victor Laurent  # 国际化精英风格姓名
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
url: https://luxe-chronicle.com  # 需替换为真实域名
permalink: /insights/:title/  # 更简洁优雅的URL结构
pretty_urls:
  trailing_index: false  # 移除index.html后缀
  trailing_html: false   # 移除.html后缀

# 新增精英化功能配置
custom_fields:
  membership_tier:  # 会员等级体系
    - Platinum
    - Diamond 
    - Concierge
  private_club: true  # 私密俱乐部功能

# 国际化配置
i18n:
  VIP_contact: "尊享顾问专线：400-900-8888"  # 高端客服信息

# 首页生成器强化
index_generator:
  per_page: 12  # 符合高端用户阅读习惯
  order_by: -updated  # 优先显示最新更新内容

# 分类标签升级
default_category: elite_lifestyle  # 默认分类改为"精英生活"
category_map:
  私人飞行: /aviation  # 高端分类映射
  游艇鉴赏: /yachting

# 增强元数据
meta_generator: false  # 隐藏生成器信息提升私密性
